### ISSUE TITLE
000006_Jazz Bass(2F)P.ini stange NoteLimitLow values

### ISSUE THREAD

**Issue by probonopd** [BobanSpasic/MDX_Vault#3] opened 2023-12-02 23:51 UTC
[000006_Jazz Bass(2F)P.ini](https://github.com/BobanSpasic/MDX_Vault/blob/main/TX802/Factory/000006_Jazz%20Bass(2F)P.ini) works only from middle D upwards and sounds differently from middle G upwards.

`NoteLimitLowX` is `61` for some voices and `67` for others.

Is this intentional?

**Comment by BobanSpasic** [comment] 2023-12-02 23:57
I see. The split points are like in the original file. The problem is that these channels should be muted.

**Comment by probonopd** [comment] 2023-12-03 00:26
Interestingly, the demo at https://www.youtube.com/watch?v=Z2z9q8sh-5U&t=107s is also entirely silent and is skipped in that video.

**Comment by BobanSpasic** [comment] 2023-12-03 11:16
The fix will be included in the next commit. It was a wrong processing of VoiceChannelOffset parameter, and not all the voices were muted that should be muted (the ones wit LowNote 67)

**Closed** 2023-12-03 17:21 UTC

**Comment by BobanSpasic** [comment] 2023-12-03 19:17
Probably related to https://github.com/BobanSpasic/MDX_Vault/issues/5
